# Course Materials

For convenience, we've put together links to all the course materials on this page. You can also download a zipped folder containing the R Markdown files & pdf slides: [2021-06-30_r-for-humanities_course-materials.zip](https://github.com/UtrechtUniversity/workshop-r-for-humanities/raw/main/2021-06-30_r-for-humanities_course-materials.zip)

### Introduction {-}

[Introduction Slides](https://github.com/UtrechtUniversity/workshop-r-for-humanities/raw/main/slides/pdf/0_introduction_slides.pdf)

### Base R {-}

- Link to Base R exercises in R Markdown: [baseR_exercises.Rmd](https://github.com/UtrechtUniversity/workshop-r-for-humanities/blob/main/exercises/baseR_exercises.Rmd). 

FYI: The R Markdown file will not download automatically. The slides are in HTML and can be opened in new tabs (if more convenient). The same goes for the videos which are available on YouTube.

| Subject | Slides | Video | Exercise | Solution Slide | Solution Video |
|:--------|:-------|:------|:---------|:-------------|:-------------|
| R Syntax & data types | [Slides](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#18) | [Video](https://youtu.be/S8zTmEvpYYk) | Exercise 1 | [Solution Slide](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#27) | [Solution Video](https://youtu.be/V8za6GR7u8Q) |
| Vectors in R | [Slides](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#28) | [Video](https://youtu.be/XMFjteCdHbQ) | Exercise 2 | [Solution Slide](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#40) | [Solution video](https://youtu.be/rIieuoYT4z0) |
| Data structures | [Slides](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#41) | [Video](https://youtu.be/Ffk2Kxa_b_M) | Exercise 3 | [Solution Slide](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#50) | [Solution Video](https://youtu.be/A1GsHC6pIio) |
| Missing data | [Slides](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#53) | [Video](https://youtu.be/4gVvlg1Itzs) | Exercise 4 | [Solution Slide](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#63) | - |
| Indexing vectors & lists | [Slides](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#66) | [Video](https://youtu.be/e10nO2swYIE) | Exercise 5 | [Solution Slide](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#79) | [Solution Video](https://youtu.be/4BZGGq-nBos) |
| Indexing a data frame | [Slides](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#80) | [Video](https://youtu.be/m15hbXG6I-Y) | Exercise 6 | [Soltion Slide](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#91) | [Solution Video](https://youtu.be/DUk9bfcSwbA) |

### Textmining with Tidy Text {-}

- Link to Tidy Text exercises document in R Markdown: [tidytext_exercises.Rmd](https://github.com/UtrechtUniversity/workshop-r-for-humanities/blob/main/exercises/tidytext_exercises.Rmd)
- Link to Tidy Text solutions document in R Markdown: [tidytext_codingsolutions.Rmd](https://github.com/UtrechtUniversity/workshop-r-for-humanities/blob/main/exercises/tidytext_codingsolutions.Rmd)

FYI: The R Markdown files won't download automatically, but the slides for this section, which are in pdf format, will land on your computer somewhere.

| Subject | Slides | Exercise | Solution Slide | 
|:--------|:-------|:---------|:-------------|
| Tidy Text Format | [Slides](https://github.com/UtrechtUniversity/workshop-r-for-humanities/raw/main/slides/pdf/1_tidy-text_slides.pdf) | Exercises 7 & 8 | [Slides](https://github.com/UtrechtUniversity/workshop-r-for-humanities/raw/main/slides/pdf/1_tidy-text_solution.pdf)
| Sentiment Analysis| [Slides](https://github.com/UtrechtUniversity/workshop-r-for-humanities/raw/main/slides/pdf/2_sentiment-analysis_slides.pdf) | Exercise 9 | [Slides](https://github.com/UtrechtUniversity/workshop-r-for-humanities/raw/main/slides/pdf/2_sentiment-analysis_solution.pdf)
| Word & Document Frequency | [Slides](https://github.com/UtrechtUniversity/workshop-r-for-humanities/raw/main/slides/pdf/3_word-and-document-frequency_slides.pdf) | Exercise 10 | [Slides](https://github.com/UtrechtUniversity/workshop-r-for-humanities/raw/main/slides/pdf/3_word-and-document-frequency_solution.pdf)
| Relationships Between Words | [Slides](https://github.com/UtrechtUniversity/workshop-r-for-humanities/raw/main/slides/pdf/4_relationships-between-words_slides.pdf) | Exercises 11 & 12 | [Slides](https://github.com/UtrechtUniversity/workshop-r-for-humanities/raw/main/slides/pdf/4_relationships-between-words_solution.pdf)
